using System.Collections.ObjectModel;
using System.IO;
using System.Reflection;
using System.Windows;
using BauProjektManager.Domain.Enums;
using BauProjektManager.Domain.Models;
using BauProjektManager.Infrastructure.Persistence;
using BauProjektManager.Settings.Views;
using CommunityToolkit.Mvvm.ComponentModel;
using CommunityToolkit.Mvvm.Input;
using Serilog;

namespace BauProjektManager.Settings.ViewModels;

/// <summary>
/// ViewModel for the Settings page — manages project list via SQLite.
/// Automatically exports registry.json after every change.
/// </summary>
public partial class SettingsViewModel : ObservableObject
{
    private readonly ProjectDatabase _db = new();
    private readonly RegistryJsonExporter _exporter;

    [ObservableProperty]
    private ObservableCollection<Project> _projects = [];

    [ObservableProperty]
    private Project? _selectedProject;

    [ObservableProperty]
    private string _registryStatus = "";

    public SettingsViewModel()
    {
        // Export folder next to the app root
        var appRoot = FindAppRoot();
        var exportDir = Path.Combine(appRoot, "Export");
        var registryPath = Path.Combine(exportDir, "registry.json");

        _exporter = new RegistryJsonExporter(registryPath);

        Log.Information("App root: {Root}", appRoot);
        Log.Information("Registry export path: {Path}", registryPath);

        LoadProjects();
    }

    /// <summary>
    /// Finds the app root folder (where the .slnx or .sln file is).
    /// Works both in Debug (bin/Debug/...) and deployed scenarios.
    /// </summary>
    private static string FindAppRoot()
    {
        // Start from the exe location
        var dir = AppDomain.CurrentDomain.BaseDirectory;

        // Walk up until we find the solution file or run out of parents
        var current = new DirectoryInfo(dir);
        while (current is not null)
        {
            if (current.GetFiles("*.slnx").Length > 0 ||
                current.GetFiles("*.sln").Length > 0)
            {
                return current.FullName;
            }
            current = current.Parent;
        }

        // Fallback: use exe directory
        return dir;
    }

    private void LoadProjects()
    {
        try
        {
            var loaded = _db.LoadAllProjects();
            Projects = new ObservableCollection<Project>(loaded);
            Log.Information("Loaded {Count} projects from database", loaded.Count);
            RegistryStatus = $"{loaded.Count} Projekte geladen";
        }
        catch (Exception ex)
        {
            Log.Error(ex, "Failed to load projects from database");
            Projects = [];
            RegistryStatus = "Fehler beim Laden!";
        }
    }

    private void ExportRegistry()
    {
        try
        {
            _exporter.Export(Projects.ToList());
            RegistryStatus = $"Registry exportiert ({Projects.Count} Projekte)";
        }
        catch (Exception ex)
        {
            Log.Error(ex, "Failed to export registry.json");
            RegistryStatus = "Registry-Export fehlgeschlagen!";
        }
    }

    [RelayCommand]
    private void AddProject()
    {
        var newProject = new Project
        {
            Id = "",  // Will be auto-generated by DB
            Status = ProjectStatus.Active,
            Timeline = new ProjectTimeline
            {
                ProjectStart = DateTime.Today
            }
        };
        newProject.UpdateProjectNumberFromStart();

        var dialog = new ProjectEditDialog(newProject);
        dialog.Owner = Application.Current.MainWindow;
        if (dialog.ShowDialog() == true)
        {
            try
            {
                _db.SaveProject(dialog.Project);
                Projects.Add(dialog.Project);
                SelectedProject = dialog.Project;
                ExportRegistry();
                Log.Information("Project added: {Name} ({Number})", dialog.Project.Name, dialog.Project.ProjectNumber);
            }
            catch (Exception ex)
            {
                Log.Error(ex, "Failed to save new project");
                MessageBox.Show($"Fehler beim Speichern: {ex.Message}", "Fehler",
                    MessageBoxButton.OK, MessageBoxImage.Error);
            }
        }
    }

    [RelayCommand]
    private void EditProject()
    {
        if (SelectedProject is null) return;

        var dialog = new ProjectEditDialog(SelectedProject);
        dialog.Owner = Application.Current.MainWindow;
        if (dialog.ShowDialog() == true)
        {
            try
            {
                _db.SaveProject(dialog.Project);
                // ObservableCollection refreshen
                int index = Projects.IndexOf(SelectedProject);
                if (index >= 0)
                {
                    Projects[index] = dialog.Project;
                    SelectedProject = dialog.Project;
                }
                ExportRegistry();
                Log.Information("Project updated: {Name} ({Number})", dialog.Project.Name, dialog.Project.ProjectNumber);
            }
            catch (Exception ex)
            {
                Log.Error(ex, "Failed to update project");
                MessageBox.Show($"Fehler beim Speichern: {ex.Message}", "Fehler",
                    MessageBoxButton.OK, MessageBoxImage.Error);
            }
        }
    }
}
